version: "3.5"
services:
  mysql:
    image: mysql:8.0.11
    # https://stackoverflow.com/questions/51670095/docker-flyway-mysql-8-client-does-not-support-authentication-protocol-requeste
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3406:3306
    restart: always
    environment:
      - MYSQL_DATABASE=demo_credit
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - demo_credit_volume:/data/db
    networks:
      - demo_credit_network

  demo_credit_microservices:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - DB_NAME=demo_credit
    ports:
      - 80:3000
    networks:
      - demo_credit_network

networks:
  demo_credit_network:
    name: demo_credit_network

volumes:
  demo_credit_volume:
    name: demo_credit_volume
